development:
  adapter: mysql2
  encoding: utf8
  database: mj_tsumotter_dev
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: mj_tsumotter_pro
  database: msuke_pro
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: mj_tsumotter_test
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
